# Generated by Django 3.0 on 2021-04-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210424_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handicrafts',
            old_name='upload',
            new_name='da',
        ),
    ]
